const int pinoChave = 7; //PINO DIGITAL UTILIZADO PELA CHAVE FIM DE CURSO
 
void setup() {
pinMode(pinoChave, INPUT_PULLUP); //DEFINE O PINO COMO ENTRADA / "_PULLUP" É PARA ATIVAR O RESISTOR INTERNO
  //DO ARDUINO PARA GARANTIR QUE NÃO EXISTA FLUTUAÇÃO ENTRE 0 (LOW) E 1 (HIGH)
}
void loop(){
  
}